SkylabCoders/skylab-bootcamp-202007

anna-codina/airplanes-js/airlines-pro.js
anna-codina/airplanes-js/airlines.js
anna-codina/bingo-js/bingo.js
anna-codina/calculadora-js/calculator-pro.js
anna-codina/calculadora-js/calculator.js
anna-codina/calculator-html/index.css
anna-codina/calculator-html/index.html
anna-codina/calculator-html/index.js
anna-codina/conecta4/index.html
anna-codina/conecta4/main.js
anna-codina/conecta4/style.css
anna-codina/pasapalabra-html/index.css
anna-codina/pasapalabra-html/index.html
anna-codina/pasapalabra-html/index.js
anna-codina/pasapalabra-js/pasapalabra.js

Anna codina

---

alex-larranaga/tema1/calculator-pro.js
alex-larranaga/tema1/calculator.js
alex-larranaga/tema2/airlines.js
alex-larranaga/tema3/bingo.js
alex-larranaga/tema4/pasapalabra.js

Pull Request to merge branch "alex-larranaga" into master

Alex larranaga

---

victor-alemany/airlines/airlines-pro.js
victor-alemany/airlines/airlines.js
victor-alemany/bingo/bingo.js
victor-alemany/calculator-html/calculator-html.html
victor-alemany/calculator-html/index.css
victor-alemany/calculator-html/index.js
victor-alemany/calculator/calculator-pro.js
victor-alemany/calculator/calculator.js
victor-alemany/pasapalabra/pasapalabra.js

- Se promociona el código del proyecto calculadora que contiene los ficheros calculator.js y calculator-pro.js

Push del primer proyecto del prebootcamp skylab

---

Dani-Alcala/Dani-Alcala-Precourse/Airlines/airlines-pro.js
Dani-Alcala/Dani-Alcala-Precourse/Airlines/airlines.js
Dani-Alcala/Dani-Alcala-Precourse/Bingo/bingo-15-numeros.js
Dani-Alcala/Dani-Alcala-Precourse/Bingo/bingo-5-numeros.js
Dani-Alcala/Dani-Alcala-Precourse/Bingo/bingo-pro.js
Dani-Alcala/Dani-Alcala-Precourse/Calculator-html/calculator-2.js
Dani-Alcala/Dani-Alcala-Precourse/Calculator-html/calculator.css
Dani-Alcala/Dani-Alcala-Precourse/Calculator-html/calculator.html
Dani-Alcala/Dani-Alcala-Precourse/Calculator/calculator-pro.js
Dani-Alcala/Dani-Alcala-Precourse/Calculator/calculator.js
Dani-Alcala/Dani-Alcala-Precourse/Pasapalabra-html/pasapalabra-2.js
Dani-Alcala/Dani-Alcala-Precourse/Pasapalabra-html/pasapalabra.css
Dani-Alcala/Dani-Alcala-Precourse/Pasapalabra-html/pasapalabra.html
Dani-Alcala/Dani-Alcala-Precourse/Pasapalabra/pasapalabra.js

I added all the precourse projects

Dani alcala

---

aleix-sanllehy/1-calculator/calculator.js
aleix-sanllehy/2-airlines/airlines.js
aleix-sanllehy/3-bingo/bingo.js
aleix-sanllehy/4-pasapalabra/pasapalabra.js

Branch aleix-sanllehy to merge with master

Aleix sanllehy

---

fcesc/challenge2.css
fcesc/challenge2.html
fcesc/challenge2.js
fcesc/test-estilos.css
fcesc/test.html
fcesc/test2.html
fcesc/test2.js

Fcesc challenge2

---

fcesc/challenge3_flexbox/css/styles.css
fcesc/challenge3_flexbox/index.html
fcesc/challenge3_flexbox/js/coolstuff.js
fcesc/challenge3_flexbox/pages/about.html
fcesc/challenge3_flexbox/pages/applepie.html
fcesc/challenge3_flexbox/pages/cheesecakes.html
fcesc/challenge3_flexbox/pages/fruitpies.html
fcesc/challenge3_flexbox/pages/pieoverview.html
fcesc/challenge3_flexbox/pages/seasonalpies.html

[fcesc] challenge3 flexbox

---

pablo-hortelano/flexbox/flex-mini-exercise/flexbox.css
pablo-hortelano/flexbox/flex-mini-exercise/flexbox.html

Day 3 lecture's exercises Skylab Coders Academy

[pablo] lecture-day3-flex

---

victor-alemany/flexbox/flexbox.css
victor-alemany/flexbox/flexbox.html

Request to add all files of the flexbox lesson

[valemany]Flexbox lesson

---

anna-codina/flexbox/flexbox.css
anna-codina/flexbox/flexbox.html

new flexbox folder
new flexbox.html
new flexbox.css

[Anna]Flexbox Lecture

---

dani-Alonso/flexbox/flexbox.css
dani-Alonso/flexbox/flexbox.html

[Dani Alonso]Flexbox

---

santiago-robinet/flexbox-challenge/css/styles.css
santiago-robinet/flexbox-challenge/index.html
santiago-robinet/flexbox-challenge/pages/applepie.html
santiago-robinet/flexbox-challenge/pages/cheesecakes.html
santiago-robinet/flexbox-challenge/pages/fruitpies.html
santiago-robinet/flexbox-challenge/pages/pieoverview.html
santiago-robinet/flexbox-challenge/pages/seasonalpies.html
santiago-robinet/flexbox-challenge/pages/test.html

- Cards added
-  Navigator spacing
NOT FINISHED!!

[Santi] Flexbox-day-two 

---

victor-alemany/challengeFlexbox/css/styles.css
victor-alemany/challengeFlexbox/pages/applepie.html
victor-alemany/challengeFlexbox/pages/cheesecakes.html
victor-alemany/challengeFlexbox/pages/fruitpies.html
victor-alemany/challengeFlexbox/pages/pieoverview.html
victor-alemany/challengeFlexbox/pages/seasonalpies.html

Requesting merge my branch against master with last updated flexbox project

[valemany]flexbox

---

fcesc/challenge3_flexbox/css/styles.css
fcesc/challenge3_flexbox/index.html
fcesc/challenge3_flexbox/pages/about.html
fcesc/challenge3_flexbox/pages/applepie.html
fcesc/challenge3_flexbox/pages/cheesecakes.html
fcesc/challenge3_flexbox/pages/data.html
fcesc/challenge3_flexbox/pages/fruitpies.html
fcesc/challenge3_flexbox/pages/seasonalpies.html
fcesc/challenge3_flexbox/pages/test.html

Challenge 3 upgrade - responsive & flex tables

[fcesc] challenge3upgrade

---

victor-alemany/clousures/callbacks.js
victor-alemany/clousures/clousures.js
victor-alemany/clousures/this.js

Adding lecture and challenge of clousures,callbacks and this resources

[valemany]clousures-callbacks-this

---

fcesc/challenge5_rakuten/index.html
fcesc/challenge5_rakuten/styles.css
fcesc/challenge6_strictEquals/challenge6.html
fcesc/challenge6_strictEquals/challenge6.js
fcesc/challenge_gameOfLife/gameOfLife.css
fcesc/challenge_gameOfLife/gameOfLife.html
fcesc/challenge_gameOfLife/gameOfLife.js

Version 1.0 game of life challenge.

[fcesc] challenge - game of life

---

victor-alemany/gameoflife/index.html
victor-alemany/gameoflife/main.js
victor-alemany/gameoflife/style.css

Requesting merge for add all features of game of life challenge

[valemany]challenge-gameoflife

---

victor-alemany/review-clousures/README.md
victor-alemany/review-clousures/review-clousures.js
victor-alemany/review-clousures/reviewClousures-test.html
victor-alemany/review-clousures/spect-reviewClousures.js

review lecture of clousures and functions

[valemany]clousures-review

---

victor-alemany/tourofheroes/README.md
victor-alemany/tourofheroes/details/details.html
victor-alemany/tourofheroes/details/details.js
victor-alemany/tourofheroes/hero-detail/hero-detail.component.css
victor-alemany/tourofheroes/hero-detail/hero-detail.component.html
victor-alemany/tourofheroes/hero-detail/hero-detail.component.js
victor-alemany/tourofheroes/hero-detail/hero-detail.component.spec.js
victor-alemany/tourofheroes/hero-detail/hero-detail.component.test.html
victor-alemany/tourofheroes/hero-list/hero-list.component.css
victor-alemany/tourofheroes/hero-list/hero-list.component.html
victor-alemany/tourofheroes/hero-list/hero-list.component.js
victor-alemany/tourofheroes/hero-list/hero-list.component.spec.js
victor-alemany/tourofheroes/hero-list/hero-list.component.test.html
victor-alemany/tourofheroes/hero.data.js
victor-alemany/tourofheroes/hero.js
victor-alemany/tourofheroes/test-tourofheroes.html
victor-alemany/tourofheroes/tourofheroes-spect.js

[valemany]tourofheroes

---

victor-alemany/bingo/bingo.js

[valemany]bingo precourse hotfix

---

victor-alemany/rakuten-challenge/style.css

Adding hotfixes to rakuten project

[valemany] Rakuten hotfix

---

victor-alemany/clousures/callbacks.js
victor-alemany/clousures/clousures.js
victor-alemany/clousures/this.js

Adding hotfixes to files of callbacks-clousures-this lectures

[valemany] hotfix callbacks-clousures-this

---

victor-alemany/gameoflife/index.html
victor-alemany/gameoflife/main.js
victor-alemany/gameoflife/style.css

Adding hotfixes to gameoflife project

[valemany]game of life hotfixes

---

aleix-sanllehy/challenge-tour-of-heroes/hero-dashboard/hero-dashboard.component.css
aleix-sanllehy/challenge-tour-of-heroes/hero-dashboard/hero-dashboard.component.html
aleix-sanllehy/challenge-tour-of-heroes/hero-dashboard/hero-dashboard.component.js
aleix-sanllehy/challenge-tour-of-heroes/hero-detail/hero-detail.component.html
aleix-sanllehy/challenge-tour-of-heroes/hero-detail/hero-detail.component.js
aleix-sanllehy/challenge-tour-of-heroes/hero-list.json
aleix-sanllehy/challenge-tour-of-heroes/hero-list/hero-list.component.css
aleix-sanllehy/challenge-tour-of-heroes/hero-list/hero-list.component.html
aleix-sanllehy/challenge-tour-of-heroes/hero-list/hero-list.component.js
aleix-sanllehy/challenge-tour-of-heroes/hero-service/hero.service.js
aleix-sanllehy/challenge-tour-of-heroes/hero.mock.js

[aleix] lecture - tour of heroes with fetch

---

fcesc/challenge_tour-of-heroes/heroQuery-component/heroQueries.js
fcesc/challenge_tour-of-heroes/jasmine.html
fcesc/challenge_tour-of-heroes/services/hero.service.spec.js
fcesc/challenge_tour-of-heroes/services/hero.service_PROMISES.js

[fcesc] - update tour of heroes

---

.gitignore

sup lads! if you may find some time, kindly check the updated .gitignore. 
thumbs up if it looks nice, otherwise let me know.
cheers!

added ignore for media files

---

ProjectGGJ/projectggj/src/components/homeComponent/homeComponent.js
ProjectGGJ/projectggj/src/components/planetComponent/planetComponent.js
ProjectGGJ/projectggj/src/index.js
ProjectGGJ/projectggj/src/sagaComponent/sagaComponent.js

created sagaComponent and homeComponent
added functions works in sagaComponent, homeComponent, planetComponent and index.js

added functions and created files

---

fcesc/.gitignore
fcesc/reactoh/.eslintrc.js
fcesc/reactoh/package.json
fcesc/reactoh/src/AppDispatcher.js
fcesc/reactoh/src/actions/actionTypes.js
fcesc/reactoh/src/actions/heroActions copy.js
fcesc/reactoh/src/actions/heroActions.js
fcesc/reactoh/src/components/App copy.js
fcesc/reactoh/src/components/App.js
fcesc/reactoh/src/components/App_PREVIOUS.js
fcesc/reactoh/src/components/Footer.js
fcesc/reactoh/src/components/FullList.js
fcesc/reactoh/src/components/Header.js
fcesc/reactoh/src/components/HeroDetail copy.js
fcesc/reactoh/src/components/HeroDetail.js
fcesc/reactoh/src/components/MainMenu.css
fcesc/reactoh/src/components/MainMenu.js
fcesc/reactoh/src/components/OldPaginatedList.js
fcesc/reactoh/src/components/PageNotFound.css
fcesc/reactoh/src/components/PageNotFound.js
fcesc/reactoh/src/components/PaginatedList.css
fcesc/reactoh/src/components/TopHeroes.js
fcesc/reactoh/src/index.js
fcesc/reactoh/src/services/hero.service.js
fcesc/reactoh/src/stores/heroStore.js

[fcesc] update toh

---

00-GROUP-CHALLENGE/04-polke/src/components/Landing/Login/Login-styles.css
00-GROUP-CHALLENGE/04-polke/src/components/Landing/Login/Login.js

Media Queries changed to standard

Refactoring styles

---

00-GROUP-CHALLENGE/04-polke/src/components/Landing/Landing.js
00-GROUP-CHALLENGE/04-polke/src/components/Landing/Login/Login.js
00-GROUP-CHALLENGE/04-polke/src/components/Landing/PopUpBox/PopUpBox-styles.css
00-GROUP-CHALLENGE/04-polke/src/components/Landing/PopUpBox/PopUpBox.js

[Pablo]Adding PopUpBox component ->  src/components/Landing/PopUpBox

---

aleix-sanllehy/toh-express/index.js
aleix-sanllehy/toh-express/src/routes/authRoutes.js
aleix-sanllehy/toh-express/src/routes/heroRoutes.js
aleix-sanllehy/toh-express/src/views/auth/profile.ejs

Pending: 
- 8 to 12 characters
- at least one capital letter
- at least one number 
- at least one character from this list [!#/()=*]
- Show message below the input  when not valid

[aleix] toh-nodejs
